spring:
  sql:
    init:
      data-locations:
        classpath:/data/performance-test-data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:chat-api
    driverClassName: org.h2.Driver
    username: sa
    password: sa